<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW6FXsz6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW6FXsz6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW6FXsz6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW6FXsz6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW6FXsz6\App_KernelDevDebugContainer([
    'container.build_hash' => 'W6FXsz6',
    'container.build_id' => 'd67e8845',
    'container.build_time' => 1621975304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW6FXsz6');
