<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOi6EbV3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOi6EbV3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOi6EbV3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOi6EbV3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOi6EbV3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oi6EbV3',
    'container.build_id' => 'e7d31645',
    'container.build_time' => 1616320142,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOi6EbV3');
