<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP88OmFo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP88OmFo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP88OmFo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP88OmFo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP88OmFo\App_KernelDevDebugContainer([
    'container.build_hash' => 'P88OmFo',
    'container.build_id' => 'bd8b8839',
    'container.build_time' => 1616967698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP88OmFo');
